apiVersion: apps/v1
kind: Deployment
metadata:
  name: air-quality-monitoring
spec:
  replicas: 3
  selector:
    matchLabels:
      component: web
  template:
    metadata:
      labels:
        component: web
    spec:
      containers:
        - name: client
          image: ikoushikghosh/air-quality-monitoring:latest
          ports:
            - containerPort: 4200
